"""empty message

Revision ID: 0bed1dd8d672
Revises: 73b671e0a13e
Create Date: 2022-06-27 18:59:13.350166

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0bed1dd8d672'
down_revision = '73b671e0a13e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itemsWB', sa.Column('history', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('itemsWB', 'history')
    # ### end Alembic commands ###
