"""empty message

Revision ID: 73b671e0a13e
Revises: 12b776cdfce6
Create Date: 2022-06-20 13:08:12.005321

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '73b671e0a13e'
down_revision = '12b776cdfce6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itemsWB',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('brand', sa.String(length=200), nullable=True),
    sa.Column('sale_price', sa.Float(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('link', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_itemsOZON_link', table_name='itemsOZON')
    op.drop_index('ix_itemsOZON_title', table_name='itemsOZON')
    op.drop_table('itemsOZON')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itemsOZON',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"itemsOZON_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('brand', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('final_price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('link', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('rating', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='itemsOZON_pkey')
    )
    op.create_index('ix_itemsOZON_title', 'itemsOZON', ['title'], unique=False)
    op.create_index('ix_itemsOZON_link', 'itemsOZON', ['link'], unique=False)
    op.drop_table('itemsWB')
    # ### end Alembic commands ###
